service: cloud-utils # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  ping:
    handler: handler.ping
    timeout: 30
    memorySize: 128
    events:
      - http:
          path: /ping
          method: get

package:
  exclude:
    - node_modules/**
    - test/**
    - .vscode/**
    - package*.json
    - README.md
    - .gitignore
    - LICENSE
#    - '!node_modules/node-fetch/**'